# Generated by Django 4.2.1 on 2024-03-19 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_course_options_alter_lecturer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
